# This file was generated by GoReleaser. DO NOT EDIT.
cask "thg" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "04e2a4770fc0a15168614d0b219f88f6ccb22b7a4f54ad289210daee4384fe91"
      url "https://github.com/andrew-craig/thg/releases/download/v#{version}/thg-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "36560ea06e9b5784b7924280347707256e8d7a289ccdc8653b2fbea33eee9010"
      url "https://github.com/andrew-craig/thg/releases/download/v#{version}/thg-darwin-arm64.tar.gz"
    end
  end

  name "thg"
  desc "Command-line interface for reading and writing tasks in Things 3"
  homepage "https://github.com/andrew-craig/thg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thg"

  # No zap stanza required

end
