# This file was generated by GoReleaser. DO NOT EDIT.
cask "thg" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "ec6615f8b025c33c685653105b2a0b3480c8595d98815342b350a6b0b744ee09"
      url "https://github.com/andrew-craig/thg/releases/download/v#{version}/thg-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "5331a7103b001df754ddefa5737601000729f9824588117a0417e24ad443cdb3"
      url "https://github.com/andrew-craig/thg/releases/download/v#{version}/thg-darwin-arm64.tar.gz"
    end
  end

  name "thg"
  desc "Command-line interface for reading and writing tasks in Things 3"
  homepage "https://github.com/andrew-craig/thg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thg"

  # No zap stanza required

end
